### ISSUE TITLE
I keep loosing the ability to cast spells and die due to overlay - solution?

### ISSUE THREAD

**Issue by ryanadanderson** [Colorfulstan/overwolf-champ101#3]
Issue - i am unable to cast spells or interact with game when I try to move my map up and accidentally hover over the overlay. 

I think a small movable activate button would be nice so that I can use it to interact with it when I want. After so long (or maybe when my curser leaved the overlay), a time out would happen so the bar as a whole becomes unclickable so that I dont accidentally keep clicking it and dying.

**Comment by Colorfulstan** [comment]
You can hide it completely by using ctrl + shift + space, so it doesn't get in your way.
